//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CyberSolitaire.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_DEBUG                       101
#define IDR_MAINFRAME                   128
#define IDR_CYBSOLTYPE                  129
#define IDR_SELECTFRAME                 130
#define IDI_CYBERSOLITAIREDOC           130
#define IDR_SOLEDITTYPE                 131
#define IDB_BITMAP66                    132
#define IDB_SELECTEDMASK                132
#define IDR_TTT_TYPE                    132
#define IDB_START_CARD                  134
#define IDB_BITMAP70                    134
#define IDB_BITMAP71                    135
#define IDB_BITMAP72                    136
#define IDB_BITMAP73                    137
#define IDB_BITMAP74                    138
#define IDB_BITMAP75                    139
#define IDB_BITMAP76                    140
#define IDB_BITMAP77                    141
#define IDB_BITMAP78                    142
#define IDB_BITMAP79                    143
#define IDB_BITMAP80                    144
#define IDB_BITMAP81                    145
#define IDB_BITMAP82                    146
#define IDB_BITMAP83                    147
#define IDB_BITMAP84                    148
#define IDB_BITMAP85                    149
#define IDB_BITMAP86                    150
#define IDB_BITMAP87                    151
#define IDB_BITMAP88                    152
#define IDB_BITMAP89                    153
#define IDB_BITMAP90                    154
#define IDB_BITMAP91                    155
#define IDB_BITMAP92                    156
#define IDB_BITMAP93                    157
#define IDB_BITMAP94                    158
#define IDB_BITMAP95                    159
#define IDB_BITMAP96                    160
#define IDB_BITMAP97                    161
#define IDB_BITMAP98                    162
#define IDB_BITMAP99                    163
#define IDB_BITMAP100                   164
#define IDB_BITMAP101                   165
#define IDB_BITMAP102                   166
#define IDB_BITMAP103                   167
#define IDB_BITMAP104                   168
#define IDB_BITMAP105                   169
#define IDB_BITMAP106                   170
#define IDB_BITMAP107                   171
#define IDB_BITMAP108                   172
#define IDB_BITMAP109                   173
#define IDB_BITMAP110                   174
#define IDB_BITMAP111                   175
#define IDB_BITMAP112                   176
#define IDB_BITMAP113                   177
#define IDB_BITMAP114                   178
#define IDB_BITMAP115                   179
#define IDB_BITMAP116                   180
#define IDB_BITMAP117                   181
#define IDB_BITMAP118                   182
#define IDB_BITMAP119                   183
#define IDB_BITMAP120                   184
#define IDB_BITMAP121                   185
#define IDB_EMPTY_CARD                  186
#define IDB_END_CARD                    186
#define IDD_SHOW_PILE                   192
#define IDR_PILECONTEXT                 193
#define IDR_SHOWTOOLBAR                 194
#define IDB_EMPTY_START                 200
#define IDB_TABLEAU1                    200
#define IDB_EMPTY1                      200
#define IDS_PROGRAM_VERSION             200
#define IDB_BITMAP68                    201
#define IDB_EMPTY2                      201
#define IDB_BITMAP67                    202
#define IDB_EMPTY3                      202
#define IDB_FOUNDATION1                 203
#define IDB_EMPTY4                      203
#define IDB_STOCK1                      204
#define IDB_EMPTY5                      204
#define IDB_WASTE1                      205
#define IDB_EMPTY6                      205
#define IDB_BITMAP69                    206
#define IDB_EMPTY7                      206
#define IDB_EMPTY8                      207
#define IDB_EMPTY_END                   207
#define IDB_BACK1                       246
#define IDB_BITMAP53                    247
#define IDB_BACK2                       247
#define IDB_BITMAP54                    248
#define IDB_BACK3                       248
#define IDB_BITMAP55                    249
#define IDB_BACK4                       249
#define IDB_BITMAP56                    250
#define IDB_BACK5                       250
#define IDB_BITMAP57                    251
#define IDB_BACK6                       251
#define IDB_BITMAP58                    252
#define IDB_BACK7                       252
#define IDB_BITMAP59                    253
#define IDB_BACK8                       253
#define IDB_BITMAP60                    254
#define IDB_BACK9                       254
#define IDB_BITMAP61                    255
#define IDB_BACK10                      255
#define IDB_BITMAP62                    256
#define IDB_BACK11                      256
#define IDB_BITMAP63                    257
#define IDB_BACK12                      257
#define IDB_BITMAP64                    258
#define IDB_BACK13                      258
#define IDB_BITMAP65                    259
#define IDB_BACK14                      259
#define IDB_BITMAP684                   263
#define IDB_BITMAP679                   264
#define IDB_BITMAP680                   265
#define IDB_BITMAP681                   266
#define IDB_BITMAP682                   267
#define IDB_BITMAP683                   268
#define IDB_BITMAP678                   269
#define IDR_GAME_CONTEXT                271
#define IDR_SOLEDIT_PILECONTEXT         273
#define IDD_GAME_PROPERTIES             274
#define IDR_SOLEDIT_GAMECONTEXT         276
#define IDD_PILE_PROPERTIES             277
#define IDR_MAINFRAME1                  277
#define IDD_SELECT_CARDS                279
#define IDB_BITMAP122                   280
#define ID_SOLEDITPILECONTEXT_MAXRECTLOESCHEN 284
#define ID_Menu                         285
#define ID_EINSTELLUNGEN_KARTENUNDHINTERGRUND 286
#define IDD_CARDS_AND_BACKGROUND        287
#define ID_PILECONTEXT_KARTEUMDREHEN    293
#define IDD_ERROR_REPORT                294
#define ID_BEARBEITEN_AUTO              295
#define IDD_DEBUG_PROPERTIES            296
#define ID_EINSTELLUNGEN_DEBUGEINSTELLUNGEN 297
#define IDD_INSERT_NEW_PLAYER           298
#define IDD_SELECT_PLAYER               299
#define IDB_BACKGROUND_START            300
#define IDB_BACKGROUND1                 300
#define ID_Menu300                      300
#define IDB_BACK_LITE_GREEN             301
#define IDD_SHOW_STATISTIC              301
#define IDB_BACKGROUND2                 302
#define IDR_STATISTICTYPE               302
#define IDB_BACKGROUND3                 303
#define IDB_BACKGROUND4                 304
#define IDB_BACKGROUND5                 305
#define IDB_BACKGROUND6                 306
#define IDB_BACKGROUND_END              306
#define IDD_TTT_CHOOSE_GAME             316
#define IDD_EDIT_TTT_LEVEL              317
#define IDB_LEVEL2                      319
#define IDB_LEVEL3                      320
#define IDB_LEVEL4                      321
#define IDB_LEVEL5                      322
#define IDB_LEVEL6                      323
#define IDB_LEVEL7                      324
#define IDB_LEVEL8                      325
#define IDB_LEVEL9                      326
#define IDB_LEVEL_CLEAR                 327
#define IDB_FIELD_UP                    328
#define IDB_FIELD_DOWN                  329
#define IDR_TTT_CYBSOL_GAME             329
#define IDB_FIELD_NEUTRAL               330
#define IDD_TTT_GAME_FINISHED           330
#define IDB_FIELD_CIRCLE                331
#define IDB_FIELD_CROSS                 332
#define IDS_GAME_SELECTION              1000
#define IDD_GAME_TREE                   1001
#define IDS_TEXT_NOT_FOUND              1001
#define IDC_GAME_NAME                   1001
#define ID_INDICATOR_GAME_NAME          1002
#define ID_INDICATOR_FREE1              1003
#define ID_INDICATOR_FREE2              1004
#define IDC_NUMBER_OF_DECKS             1004
#define ID_INDICATOR_SCORE              1005
#define IDC_GAME_GROUP                  1005
#define IDS_SHORTDESCRIPTOR             1006
#define IDC_SCORING                     1006
#define IDC_SPIN_EMPTY_PILE             1006
#define IDS_ONLY_ONE_STOCK_ALLOWED      1007
#define IDC_BMP_PILE_EMPTY              1007
#define IDC_X_POSITION                  1008
#define IDS_NO_GAME_NAME                1008
#define IDC_Y_POSITION                  1009
#define IDS_NUMBEROFDECKS_MUST_BE_GREATER_0 1009
#define IDC_OVERLAPP_METHOD             1010
#define IDS_GAME_EXIST                  1010
#define IDC_PILING_METHOD               1011
#define IDS_GAME_NOT_FOUND              1011
#define IDC_SELECT_METHOD               1012
#define IDS_COPY_ONLY_EXISTING_GAME     1012
#define IDC_PUT_IF_EMPTY                1013
#define IDC_FACE_AT_START               1014
#define IDC_NUMBER_AT_START             1015
#define IDC_DEAL_TO                     1016
#define IDC_CARD001                     1017
#define IDC_BMP_BASICCARD               1017
#define IDC_NUMBER_PER_MOVE             1018
#define IDC_MAX_CARDS                   1019
#define IDC_PILE_SPECIFIC               1020
#define IDC_STOCK_SPECIFIC              1020
#define IDC_NUMBER_PER_DEAL             1021
#define IDC_FOUNDATION_SPECIFIC         1022
#define IDC_CHECK_REPLAYABLE            1023
#define IDC_STATIC_NUMBER_PER_DEAL      1024
#define IDC_STATIC_DEAL_TO              1025
#define IDC_STATIC_KIND_OF_BASIC        1026
#define IDC_SPIN_BASICCARD              1027
#define IDC_STATIC_BASICCARD            1028
#define IDC_CHECK_BASICCARD_ONLY_VAL    1030
#define IDS_MRC_STARTDOCKING            1031
#define IDC_NUMBER_HIDDEN_AT_START      1031
#define IDC_CHECK1                      1032
#define IDC_CHECK_USE_FOR_ALL_PILES     1032
#define IDS_WRONG_VERSION               1032
#define IDC_CLIPCURSOR                  1032
#define IDC_EDIT_DEALORDER              1033
#define IDC_DONTCLIP2                   1033
#define IDC_REPORTGAMELAYOUTS           1033
#define IDC_EDIT_NUMBER_OF_REDEAL       1034
#define IDS_PROGRAM_FAILED              1034
#define IDC_STATIC_NUMBER_OF_REDEAL     1035
#define IDS_SECTION_DEBUG               1035
#define IDC_REDEAL_METHOD               1036
#define IDS_SECTION_PROPERTIES          1036
#define IDC_STATIC_REDEAL_METHOD        1037
#define IDS_SECTION_BARS                1037
#define IDC_EDIT_REDEALORDER            1038
#define IDC_CARDS_BACKGROUND            1038
#define IDS_SECTION_WINDOWS             1038
#define IDC_BMP_CARDSBACKGROUND         1039
#define IDC_CX_MAXSIZE                  1039
#define IDS_WINS_GAME                   1039
#define IDC_BMP_GAME_BACKGROUND         1040
#define IDC_Y_POSITION2                 1040
#define IDS_VIEW_PILE                   1040
#define IDC_CHECK_BASICCARD_ONLY_VAL2   1040
#define IDC_CHECK_BASICCARD_ONLY_COLOR  1040
#define IDC_CARDS_BACKGROUND2           1041
#define IDC_GAME_BACKGROUND             1041
#define IDC_ERROR_DESCRIPTION           1041
#define IDC_X_POSITION3                 1041
#define IDS_ASK_GAME_END                1041
#define IDC_CY_MAXSIZE                  1042
#define IDS_EXIT_RUNNING_GAME           1042
#define IDC_EDIT_NEW_PLAYER             1042
#define IDC_PERMITTED_PLAY              1043
#define IDS_EDITOR_IS_RUNNING           1043
#define IDC_INSERT_NEW_PLAYER           1043
#define IDS_TTT_IS_RUNNING              1044
#define IDC_DELETE_PLAYER               1044
#define IDS_GAME_IS_RUNNING             1045
#define IDC_GREETING_TEXT               1045
#define IDS_ONLY_ONE_INSTANCE           1046
#define IDC_OK_DIALOG                   1046
#define IDS_GREETING_TEXT               1047
#define IDC_MAX_POINTS                  1047
#define IDS_CHOOSE_PLAYER               1048
#define IDC_CHECK_SPECIAL_HANDLING      1048
#define IDS_DO_YOU_WANT_DELETE_PLAYER   1049
#define IDC_EDIT_SPECIAL_HANDLING       1049
#define IDS_TITLE_PLAYER_NAME           1050
#define IDS_TITLE_PLAYER_RANK           1051
#define IDC_UPDATE_OVERLAP              1051
#define IDS_STRING_IS_EMPTY             1052
#define IDS_EMPTY_GREETING_TEXT         1053
#define IDS_OK_TEXT                     1054
#define IDC_PLAYER1                     1054
#define IDS_OK_PLAY                     1055
#define IDS_DO_YOU_WANT_CANCEL_GAME     1056
#define IDC_PLAYER_LISTBOX              1056
#define ID_INDICATOR_PLAYER             1057
#define IDC_DISP_WINDOW                 1057
#define IDS_SECTION_CURRENTS            1058
#define IDS_DO_YOU_WANT_REALLY_DELETE   1059
#define IDC_SCROLLBAR_RESULTS           1059
#define IDS_CHOOSE_GAME                 1060
#define IDC_VERSION                     1060
#define IDS_TITLE_PLAYER_AVERAGE_PERCENT 1061
#define IDC_RADIO_GAME1                 1061
#define IDS_TITLE_PLAYER_AVERAGE_STANDARD 1062
#define IDC_RADIO_GAME2                 1062
#define ID_INDICATOR_TTT_LEVEL          1063
#define IDC_RADIO_GAME3                 1063
#define ID_INDICATOR_TTT_PLAYED_GAMES   1064
#define IDC_NEEDED_SCORE1               1064
#define ID_INDICATOR_TTT_GAME1          1065
#define IDC_NEEDED_SCORE2               1065
#define ID_INDICATOR_TTT_GAME2          1066
#define IDC_NEEDED_SCORE3               1066
#define ID_INDICATOR_TTT_GAME3          1067
#define IDC_EDIT_LEVEL1                 1068
#define IDS_NOT_TTT_SUITABLE            1068
#define IDC_EDIT_LEVEL2                 1069
#define IDC_LEVEL                       1069
#define IDS_GAME_WIN                    1069
#define IDC_EDIT_LEVEL3                 1070
#define IDC_DESCRIPTION                 1070
#define IDS_GAME_LOOSE                  1070
#define IDC_EDIT_LEVEL4                 1071
#define IDC_DESCRIPTION_SHORT           1071
#define IDC_GAME_RESULT                 1071
#define IDC_EDIT_LEVEL5                 1072
#define IDC_ACTUAL_SCORE                1072
#define IDC_EDIT_LEVEL6                 1073
#define IDC_NEEDED_SCORE                1073
#define IDC_EDIT_LEVEL7                 1074
#define IDC_EDIT_LEVEL8                 1075
#define IDC_EDIT_LEVEL9                 1076
#define IDC_BASICCARD_METHOD            2029
#define IDS_GROUP_NOTAVAILABLE          5000
#define IDS_SPIDERGROUP                 5001
#define IDS_KLONDIKEGROUP               5002
#define IDS_END_OF_GROUPS               5003
#define IDS_SCORE_NOTAVAILABLE          5100
#define IDS_SCORE_SEQ_IN_SUIT_AND_FOUNDATION 5101
#define IDS_SCORE_SEQ_NO_COLOR_AND_FOUNDATION 5102
#define IDS_SCORE_CARD_ON_FOUNDATION    5103
#define IDS_SCORE_SEQ_IN_SUIT           5104
#define IDS_END_OF_SCORING              5105
#define IDS_FAS_NOTAVAILABLE            5200
#define IDS_FAS_ALL_FACE_UP             5201
#define IDS_FAS_ALL_FACE_DOWN           5202
#define IDS_FAS_LAST_FACE_UP            5203
#define IDS_FAS_ODD_FACE_UP             5204
#define IDS_FAS_EVEN_FACE_UP            5205
#define IDS_FAS_END                     5206
#define IDS_OLM_NOTAVAILABLE            5220
#define IDS_OLM_NOT_OVERLAPPED          5221
#define IDS_OLM_DOWN_OVERLAPPED         5222
#define IDS_OLM_RIGHT_OVERLAPPED        5223
#define IDS_OLM_NOT_OVERLAPPED_HALF_DOWN 5224
#define IDS_OLM_END                     5225
#define IDS_PIL_NOTAVAILABLE            5240
#define IDS_PIL_DOWN_IN_SUIT            5241
#define IDS_PIL_DOWN_ALTERNATE          5242
#define IDS_PIL_DOWN_NO_COLOR           5243
#define IDS_PIL_UP_IN_SUIT              5244
#define IDS_PIL_UP_ALTERNATE            5245
#define IDS_PIL_UP_NO_COLOR             5246
#define IDS_PIL_WITH_GAPS               5247
#define IDS_PIL_ONLY_FROM_STOCK         5248
#define IDS_PIL_NOTHING                 5249
#define IDS_PIL_DOWN_IN_SUIT_ROLLING    5250
#define IDS_PIL_UP_IN_SUIT_ROLLING      5251
#define IDS_PIL_DOWN_ALTERNATE_ROLLING  5252
#define IDS_PIL_UP_ALTERNATE_ROLLING    5253
#define IDS_PIL_PAIRS_EQUAL_VALUE       5254
#define IDS_PIL_VALUE13_OR_KING         5255
#define IDS_PIL_UP_DOWN_NOCOLOR_ROLLING 5256
#define IDS_ONLY_FROM_TABLEAU_OR_WASTE  5257
#define IDS_PIL_ONE_FROM_TABLEAU_OR_WASTE 5257
#define IDS_PIL_ONLY_FROM_TABLEAU       5258
#define IDS_PIL_UP_SAME_SUIT            5259
#define IDS_PIL_DOWN_SAME_SUIT          5260
#define IDS_PIL_UP_DIFF_2               5261
#define IDS_PIL_UP_DIFF_2_IN_SUIT       5261
#define IDS_PIL_END                     5262
#define IDS_PIE_NOTAVAILABLE            5280
#define IDS_PIE_NO_CARD                 5281
#define IDS_PIE_BASIC_CARD              5282
#define IDS_PIE_BASIC_CARD_MINUS_1      5283
#define IDS_PIE_ACE                     5284
#define IDS_PIE_KING                    5285
#define IDS_PIE_FROM_STOCK_OR_ANY       5286
#define IDS_PIE_ANY_CARD                5287
#define IDS_PIE_ONLY_FROM_STOCK         5288
#define IDS_PIE_ONLY_FROM_AUTO_DEAL     5289
#define IDS_PIE_ONLY_FROM_TABLEAU       5290
#define IDS_PIE_END                     5291
#define IDS_DEAL_NOTAVAILABLE           5300
#define IDS_DEAL_TABLEAUS               5301
#define IDS_DEAL_WASTE                  5302
#define IDS_DEAL_END                    5303
#define IDS_BAS_NOTAVAILABLE            5320
#define IDS_BAS_FIRSTPLAYED             5321
#define IDS_BAS_FIXED                   5322
#define IDS_BAS_FIXEDLIE                5323
#define IDS_BAS_FROMSTOCK               5324
#define IDS_BAS_END                     5325
#define IDS_REDEAL_NOTAVAILABLE         5340
#define IDS_REDEAL_FOUNDATION           5341
#define IDS_REDEAL_FOUNDATION_MIX       5342
#define IDS_REDEAL_WASTE                5343
#define IDS_REDEAL_WASTE_MIX            5344
#define IDS_REDEAL_END                  5345
#define IDS_PPP_NOTAVAILABLE            5360
#define IDS_PPP_TABLEAU                 5361
#define IDS_PPP_WASTE                   5362
#define IDS_PPP_FOUNDATION              5363
#define IDS_PPP_TABLEAU_OR_FOUNDATION   5364
#define IDS_PPP_WASTE_TABLEAU_FOUNDATION 5365
#define IDS_PPP_END                     5366
#define IDS_SEL_NOTAVAILABLE            5380
#define IDS_SEL_IN_SUIT                 5381
#define IDS_SEL_ALTERNATE               5382
#define IDS_SEL_NO_COLOR                5383
#define IDS_SEL_SEQ_NO_COLOR            5383
#define IDS_SEL_LAST_OR_ALL_IN_SEQ      5384
#define IDS_SEL_LAST_OR_SEQ_IN_SUIT     5385
#define IDS_SEL_LAST_OR_SEQ_ALTERNATER  5386
#define IDS_SEL_ALL                     5387
#define IDS_SEL_LAST_OR_ALL_SEQ_IN_SUIT 5388
#define IDS_SEL_ONLY_LAST               5388
#define IDS_SEL_EXACT_ONE               5389
#define IDS_SEL_ALL_FACE_UP             5390
#define IDS_SEL_PAIRS_EQUAL_VALUE       5391
#define IDS_SEL_PAIRS_VALUE_13          5392
#define IDS_SEL_END                     5393
#define IDS_TITLE_PLAYER_NUMBER_OF_GAMES 5394
#define IDS_TITLE_PLAYER_AVERAGE        5395
#define IDC_PLAYER_LIST                 11090
#define ID_BUTTON_REDO                  32771
#define ID_BUTTON_UNDO                  32772
#define ID_SHOW_PILE                    32773
#define ID_DEBUG_0                      32774
#define ID_DEBUG_1                      32775
#define ID_DEBUG_2                      32776
#define ID_DEBUG_3                      32777
#define ID_DEBUG_4                      32778
#define ID_DEBUG_CLEAR                  32779
#define ID_SHOW_GAMETREE                32780
#define ID_SHOW_PILE_CHEATMODE          32781
#define ID_DESCRIPTION_SHORT            32782
#define ID_DESCRIPTION                  32783
#define ID_DATEI_GAMEEDITOR             32784
#define ID_EINFGEN_STOCK                32785
#define ID_EINFGEN_TABLEAU              32786
#define ID_EINFGEN_FOUNDATION           32787
#define ID_EINFGEN_WASTE                32788
#define ID_INSERT_WASTE                 32789
#define ID_INSERT_FOUNDATION            32790
#define ID_INSERT_TABLEAU               32791
#define ID_INSERT_STOCK                 32792
#define ID_SOLEDITPILECONTEXT_DELETE    32793
#define ID_SOLEDITPILECONTEXT_PROPERTIES 32794
#define ID_SOLEDITGAMECONTEXT_PROPERTIES 32795
#define ID_OPEN_GAMEEDITOR              32796
#define ID_TEST                         32797
#define ID_SOLEDITPILECONTEXT_COPY      32798
#define ID_GAME_COPY                    32799
#define ID_GAMECONTEXT_DELETE_GAME      32800
#define ID_SPIEL_NEU                    32801
#define ID_SPIEL_NOCHMAL                32802
#define ID_SHOW_CARD_CHEAT              32804
#define ID_SOLEDITPILECONTEXT_MAXRECTMAXIMAL 32805
#define ID_SOLEDITPILECONTEXT_MAXRECTINKREMENTIEREN 32806
#define ID_SOLEDITPILECONTEXT_MAXRECTDEKREMENTIEREN 32807
#define ID_MRC_ALLOWDOCKING             32808
#define ID_MRC_HIDE                     32809
#define ID_MRC_MDIFLOAT                 32810
#define ID_MRC_CUSTOMIZE                32811
#define ID_SPIEL_TICTACTOESPIELEN       32812
#define ID_TTTTEST_TEST                 32813
#define ID_SEL1_TEST                    32816
#define ID_ERROR_REPORT                 32818
#define ID_BUTTON32819                  32819
#define ID_AUTOPLAY                     32820
#define ID_SPIEL_ABBRECHEN              32821
#define ID_DATEI_SPEICHERN              32823
#define ID_GAMECONTEXT_COPY_GAME        32824
#define ID_GAMECONTEXT_STATISTIK        32825
#define ID_TTTLEVELPUNKTE               32826
#define ID_SPIEL_SPEICHERN              32827
#define ID_SPIEL_SPEICHERNUNTER         32828
#define ID_SPIEL_BACK_TO_TTT_WINDOW     32831
#define ID_GAME_EXIT                    32832
#define ID_EINSTELLUNGEN_UEBERNEHMETTTWERTE 32833
#define ID_SPIEL_TICTACTOELADEN         32834
#define ID_SPIEL_TTTSPEICHERN           32835
#define ID_SPIEL_TTTSPEICHERNUNTER      32836
#define ID_DARSTELLUNG                  32837
#define ID_DARSTELLUNG_PUNKTE           32838
#define ID_DARSTELLUNG_LINIEN           32839
#define ID_DARSTELLUNG_BALKEN           32840
#define ID_STATISTIK_LOESCHEN_ACT_PLAYER 32843
#define ID_STATISTIK_LOESCHEN_ALL_PLAYER 32844

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32845
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
